// <auto-generated />
using System;
using BookManage.cs.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManage.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251016092628_BookManage")]
    partial class BookManage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Admin")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManage.Data.Entities.Books", b =>
                {
                    b.Property<int>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("book_id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("current_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("stock_quantity")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("book_id");

                    b.ToTable("Books", "Admin");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.Customers", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"));

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("customer_id");

                    b.ToTable("Customers", "Admin");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.SaleItems", b =>
                {
                    b.Property<int>("sale_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sale_item_id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity_sold")
                        .HasColumnType("int");

                    b.Property<int>("sale_id")
                        .HasColumnType("int");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("sale_item_id");

                    b.HasIndex("book_id");

                    b.HasIndex("sale_id");

                    b.ToTable("SaleItems", "Admin");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.Sales", b =>
                {
                    b.Property<int>("sale_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sale_id"));

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("sale_date")
                        .HasColumnType("datetime2");

                    b.HasKey("sale_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Sales", "Admin");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("user_id");

                    b.ToTable("User", "Admin");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.SaleItems", b =>
                {
                    b.HasOne("BookManage.Data.Entities.Books", "Book")
                        .WithMany("SaleItems")
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManage.cs.Data.Entities.Sales", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("sale_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.Sales", b =>
                {
                    b.HasOne("BookManage.cs.Data.Entities.Customers", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BookManage.Data.Entities.Books", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.Customers", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("BookManage.cs.Data.Entities.Sales", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
